
jobs:
  build:
    executor:
      name: octo-exp/default
    steps:
      - octo-exp/install-tools
      - octo-exp/create-release:
          api_key: API-IAQ7MTYYN9J2FL0DNFZXIPC85CHYJAD5
          project: OctoPetShop
          release_number: 1.2.3
          server: https://dinindunz.octopus.app/app#
orbs:
  octo-exp: octopus-samples/octo-exp@0.0.3
version: 2.1