version: 2.1

orbs:
  octo-exp: octopus-samples/octo-exp@0.0.3

jobs:
  deploy:
    executor:
      name: octo-exp/default
    steps:
      - octo-exp/install-tools
      - checkout
      - octo-exp/pack:
          base_path: terralearn
          id: TerraLearn
          out_folder: package
          version: 1.2.9
      - octo-exp/push:
          api_key: API-IAQ7MTYYN9J2FL0DNFZXIPC85CHYJAD5
          package: package/TerraLearn.1.2.9.zip
          server: https://dinindunz.octopus.app/
      - octo-exp/create-release:
          api_key: API-IAQ7MTYYN9J2FL0DNFZXIPC85CHYJAD5
          project: TerraLearn
          release_number: 1.2.9
          server: https://dinindunz.octopus.app/

workflows:
  build-test-deploy:
    jobs:
      - deploy