name: Publish Packages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish terralearn
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: terralearn
          NUGET_KEY: oy2jl5ijvfcirh7aky6arfghvsnday7ejnjionnc4v5ejm
