name: Publish Packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Zip Release
      # You may pin to the exact commit or the version.
      # uses: TheDoctor0/zip-release@f216aacfedcd3e76b3b027ab065503438cd00d57
      uses: TheDoctor0/zip-release@0.4.2
      with:
        # Filename for archive
        filename: terralearn.zip
        # Base path for archive files
        #path: #= optional, default is .
        # Working directory before zipping
        #directory: # optional, default is .
        # List of excluded files / directories
        exclusions: terralearn/.terraform
        # Tool to use for archiving
        type: zip
